<?php

namespace Database\Seeders;

use App\Models\Clinics;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class ClinicsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Array of clinics data
        $clinics = [
            [
                'name' => 'Deo Wong MD Dermatology',
                'address' => 'Zone 045, 1725 Fajardo St, Sampaloc Zone, Manila, 1008 Metro Manila',
                'latitude' => 14.6090291,
                'longitude' => 120.9938618,
                'operation_hours' => 'Monday - Friday: 10:00 AM - 7:00 PM',
                'specialization' => 'Skin Disease',
                'phonenumber' => '09209773646',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '5',
                'years_of_operation' => '5',
                'parking_spot' => 'N/A',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '500 Php',
                'facebook_link' => 'https://www.facebook.com/sampalocderm/reviews',
                'website_link' => 'https://deoderm.ph/about/',
                'walk_ins' => ' Yes',
                'popularity' => '77K Likes',
                'logo' => Storage::url('ClinicSeederLogo/DeoWongMD.png')
            ],
            [
                'name' => "Eve's Skin Wellness Dermatology Clinic",
                'address' => '1655 Taft Ave, Malate, Manila, 1004 Metro Manila, Philippines',
                'latitude' => 14.5751757,
                'longitude' => 120.9861779,
                'operation_hours' => 'Monday - Saturaday: 10:00 AM - 7:00 PM',
                'specialization' => 'Acne',
                'phonenumber' => '09178917546',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '0',
                'years_of_operation' => '9',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '800 Php',
                'facebook_link' => 'https://www.facebook.com/evesskinwellnessdermaclinic',
                'website_link' => null,
                'walk_ins' => ' Yes, but preferred having an appointment.',
                'popularity' => '2K Likes',
                'logo' => Storage::url('ClinicSeederLogo/EvesSkinWellness.png')
            ],
            [
                'name' => 'Dermatology at Philippine General Hospital',
                'address' => 'Philippine General Hospital Out Patient Department, Padre Faura, Ermita,, Manila, Philippines',
                'latitude' => 14.5789064,
                'longitude' => 120.9831379,
                'operation_hours' => 'Monday - Friday: 7:30 AM - 12:00 PM',
                'specialization' => 'Cosmetic/Aesthetic, Pathologic dermatology, Venereology',
                'phonenumber' => '285548400',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '5',
                'years_of_operation' => '102',
                'parking_spot' => 'YES',
                'clinic_type' => 'PUBLIC',
                'consultation_fee' => 'Free for OPD',
                'facebook_link' => 'https://www.facebook.com/pghderm/about',
                'website_link' => 'https://pds.org.ph/institution/up-pgh-department-of-dermatology/',
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '16K Likes',
                'logo' => Storage::url('ClinicSeederLogo/DermatologyofPGH.png')
            ],
            [
                'name' => 'Skinovate Beauty Clinic',
                'address' => 'Cityland Manila Executive Regency, 1200 Jorge Bocobo St, Ermita, Manila, 1000 Metro Manila, Philippines',
                'latitude' => 14.5786649,
                'longitude' => 120.9797835,
                'operation_hours' => 'Monday - Sunday: 10:00 AM - 9:00 PM',
                'specialization' => 'Cosmetic/Aesthetic, Pathologic dermatology, Venereology',
                'phonenumber' => '09178308763',
                'health_cards' => 'N/A',
                'ratings' => '5',
                'years_of_operation' => '8',
                'parking_spot' => 'NO',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => 'N/A',
                'facebook_link' => 'https://www.facebook.com/mkclinicmanilaph/?referrer=services_landing_page',
                'website_link' => 'https://mkclinic.net/',
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '23K Likes',
                'logo' => Storage::url('ClinicSeederLogo/SkinovateBeautyClinic.png')
            ],
            [
                'name' => 'ThinkSkin by Cess Facial and Derma Center',
                'address' => 'Unit ABC Earnshaw Suites 856 Earnshaw Street corner, 461 Lacson Ave, Sampaloc, Manila, 1008 Metro Manila, Philippines',
                'latitude' => 14.6095037,
                'longitude' => 120.9840032,
                'operation_hours' => 'Monday - Sunday: 10:00 AM - 8:00 PM',
                'specialization' => 'Cosmetic/Aesthetic, Pathologic dermatology, Venereology',
                'phonenumber' => '09178066548',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '5',
                'years_of_operation' => '7',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '450 Php',
                'facebook_link' => 'https://www.facebook.com/thinkskinderma2',
                'website_link' => null,
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '5K Likes',
                'logo' => Storage::url('ClinicSeederLogo/ThinkSkin.png')
            ],
            [
                'name' => 'Dermclinic - SM Manila',
                'address' => 'Lower Ground Floor, SM City Manila, Natividad Lopez St. Manila City',
                'latitude' => 14.5901043,
                'longitude' => 120.9804278,
                'operation_hours' => 'Monday - Sunday: 10:00 AM - 9:00 PM',
                'specialization' => 'Acne Clear Advance',
                'phonenumber' => '09175906162',
                'health_cards' => 'N/A',
                'ratings' => '4',
                'years_of_operation' => '53',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '600 Php',
                'facebook_link' => null,
                'website_link' => null,
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '250K Likes',
                'logo' => Storage::url('ClinicSeederLogo/Dermclinic.png')
            ],
            [
                'name' => 'HOO Dermatology - Robinsons Place Manila',
                'address' => 'Pedro Gil, cor Adriatico St, Ermita, Manila, 1004 Metro Manila',
                'latitude' => 14.575969,
                'longitude' => 120.9815276,
                'operation_hours' => 'Monday - Sunday: 11:00 AM - 8:00 PM',
                'specialization' => 'Obagi',
                'phonenumber' => '09178720874',
                'health_cards' => 'N/A',
                'ratings' => '5',
                'years_of_operation' => '16',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '1,000 Php',
                'facebook_link' => null,
                'website_link' => null,
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '422K Likes',
                'logo' => Storage::url('ClinicSeederLogo/HOODermatology.png')
            ],
            [
                'name' => 'Skinovative Clinic - Manila',
                'address' => 'Arellano Ave, cor A.Roxas, Malate, Manila, 1004 Metro Manila',
                'latitude' => 14.5633398,
                'longitude' => 120.9961768,
                'operation_hours' => 'Monday - Saturday: 9:00 AM - 6:00 PM',
                'specialization' => 'Cosmetic/Aesthetic, Pathologic dermatology, Venereology',
                'phonenumber' => '0286334751',
                'health_cards' => 'N/A',
                'ratings' => '4',
                'years_of_operation' => '0',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '1,000 Php',
                'facebook_link' => null,
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '70K Likes',
                'logo' => Storage::url('ClinicSeederLogo/SkinovativeClinic.png')
            ],
            [
                'name' => 'Everlumin Aesthetic Clinic - Manila',
                'address' => '2F Vista Heights, Legarda, Quiapo, Manila',
                'latitude' => 14.59749,
                'longitude' => 120.9871724,
                'operation_hours' => 'Tuesday - Sunday: 10:00 AM - 8:00 PM',
                'specialization' => 'Aesthetics',
                'phonenumber' => '09176363156',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '5',
                'years_of_operation' => '5',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => 'Pathologic Consult Fee: 1,500 Php',
                'facebook_link' => 'https://www.facebook.com/everluminph',
                'website_link' => 'https://everluminph.com/?fbclid=IwY2xjawFGNYhleHRuA2FlbQIxMAABHdDmM6_hVmokjQlz_H6KTH5hBktNBymf_k7kG96VOsM5fAsb-VysWXdxQw_aem_LwaIezJFUO11pkewmfhZ-A',
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '3K Likes',
                'logo' => Storage::url('ClinicSeederLogo/Everlumin.png')
            ],
            [
                'name' => 'SkinSoul Advanced Dermatology and Medical Aesthetics',
                'address' => '"Unit S3, 842 Tolentino Street, Brgy 397, Sampaloc, Manila, Philippines"',
                'latitude' => 14.6057076,
                'longitude' => 120.9868613,
                'operation_hours' => 'Tuesday - Sunday: 10:00 AM - 7:00 PM',
                'specialization' => 'Aesthetics',
                'phonenumber' => '09271331386',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '0',
                'years_of_operation' => '0',
                'parking_spot' => 'NO',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '500 Php',
                'facebook_link' => 'https://www.facebook.com/profile.php?id=61550731217682',
                'website_link' => null,
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '1K Likes',
                'logo' => Storage::url('ClinicSeederLogo/SkinSoul.png')
            ],
            [
                'name' => 'Dermastrata Skin Clinic and Spa - SM Manila',
                'address' => '5th Floor SM Manila Natividad Almeda-Lopez cor. A. Villegas and, San Marcelino St, Ermita, Manila, Metro Manila',
                'latitude' => 14.5897972,
                'longitude' => 120.9801877,
                'operation_hours' => 'Monday - Sunday: 10:00 AM - 9:00 PM',
                'specialization' => 'Cosmetic/Aesthetic, Pathologic dermatology, Venereology',
                'phonenumber' => '09761989258',
                'health_cards' => 'N/A',
                'ratings' => '5',
                'years_of_operation' => '25',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '750 Php',
                'facebook_link' => null,
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '157K Likes',
                'logo' => Storage::url('ClinicSeederLogo/Dermstrata.png')
            ],
            [
                'name' => 'SkinCell Advanced Aesthetics - Manila',
                'address' => '1253 Unit 3, Mezzanine Level, New Bocobo Center, J.Bocobo corner Padre Faura Street, Ermita, 531 Padre Faura St, Ermita, Manila, 1000 Metro Manila',
                'latitude' => 14.5898818,
                'longitude' => 120.9414718,
                'operation_hours' => 'Monday - Sunday: 9:00 AM - 3:00 PM',
                'specialization' => 'Aesthetic',
                'phonenumber' => '09178322445',
                'health_cards' => 'N/A',
                'ratings' => '5',
                'years_of_operation' => '0',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => 'N/A',
                'facebook_link' => null,
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => 'N/A',
                'logo' => Storage::url('ClinicSeederLogo/SkincellAdvance.png')
            ],
            [
                'name' => 'Manila Doctors Hospital',
                'address' => '667 United Nations Ave, Ermita, Manila, 1000 Metro Manila',
                'operation_hours' => 'Monday - Saturday: 8:00 AM - 5:00 PM',
                'specialization' => 'Aesthetics',
                'phonenumber' => '09369315466',
                'latitude' => 14.5809904,
                'longitude' => 120.979189,
                'health_cards' => 'N/A',
                'ratings' => '3',
                'years_of_operation' => '17',
                'parking_spot' => 'YES',
                'clinic_type' => 'PUBLIC',
                'consultation_fee' => '750 Php',
                'facebook_link' => null,
                'website_link' => 'https://www.maniladoctors.com.ph/our-services/patient-services/aesthetics-center',
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '144K Likes',
                'logo' => Storage::url('ClinicSeederLogo/ManilaDoctors.png')
            ],
            [
                'name' => 'De Ocampo Memorial Medical Center',
                'address' => '2921 Nagtahan St. Sta.Mesa Manila, Manila, Philippines',
                'latitude' => 14.5998192,
                'longitude' => 120.997161,
                'operation_hours' => 'Always Open 24 Hours',
                'specialization' => 'N/A',
                'phonenumber' => '09239125414',
                'health_cards' => 'N/A',
                'ratings' => '0',
                'years_of_operation' => '0',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '750 Php',
                'facebook_link' => 'https://www.facebook.com/deocampommc',
                'website_link' => null,
                'walk_ins' => ' No, need to schedule an appointment first',
                'popularity' => '1K Likes',
                'logo' => Storage::url('ClinicSeederLogo/DeOcampoMemorial.png')
            ],
            [
                'name' => 'Metropolitan Medical Center',
                'address' => '1357 G. Masangkay St., Sta. Cruz, Manila',
                'operation_hours' => 'Monday - Friday: 2:00 PM - 5:00 PM, Wednesday: 10:00 AM - 4:00 PM',
                'latitude' => 14.6096623,
                'longitude' => 120.9761107,
                'specialization' => 'Medical Dermatology and Pediatric Dermatology',
                'phonenumber' => '09272444329',
                'health_cards' => 'N/A',
                'ratings' => '0',
                'years_of_operation' => '62',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '500 Php',
                'facebook_link' => 'https://www.facebook.com/MetroMedPH',
                'website_link' => 'https://metropolitanmedicalcenter.com.ph/?fbclid=IwY2xjawFSy7tleHRuA2FlbQIxMAABHQw9jQDPNlRBLWed-6GkhFZxWlIJ2LsZQD6xNfx8uFYxNLli32LFINy3_A_aem_BYp01lodEHFAGLIwBACR-w',
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '14K Likes',
                'logo' => Storage::url('ClinicSeederLogo/MetropolitanMedicalCenter.png')
            ],
            // [
            //     'name' => 'Coronel MD Clinic',
            //     'address' => '960 Matimyas St. Sampaloc, Manila Brgy 533 , Manila, Philippines',
            //     'latitude' => null,
            //     'longitude' => null,
            //     'operation_hours' => 'Monday - 9:00 AM to 11:00 AM, 
            //                             Tuesday, Thursday, SaturDay - 10:00 AM to 2:00 PM, 
            //                             Wednesday - 10:00 AM to 1:00 PM, 
            //                             Friday - By appointment',
            //     'specialization' => 'Medical Dermatology',
            //     'phonenumber' => '09295488659,
            //     'health_cards' => 'ACCEPT',
            //     'ratings' => '0',
            //     'years_of_operation' => '0',
            //     'parking_spot' => 'YES',
            //     'clinic_type' => 'PRIVATE',
            //     'consultation_fee' => '350 Php',
            //     'facebook_link' => 'https://www.facebook.com/CoronelMDClinic/',
            //     'website_link' => null,
            //     'walk_ins' => 'Walk ins or appointments are welcome',
            //     'popularity' => '1.1K Likes',
            //     'logo' => null,
            // ],
            [
                'name' => 'Dermstress Clinic',
                'address' => '12-B, Dapitan Street, corner Instruccion St, Manila City, 1000 Metro Manila',
                'latitude' => 14.6183311,
                'longitude' => 120.992923,
                'operation_hours' => 'Always Open',
                'specialization' => 'Medical and Aesthetics',
                'phonenumber' => '09178131175',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '5',
                'years_of_operation' => '18',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '300 Php',
                'facebook_link' => 'https://www.facebook.com/DermStressDapitan/',
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '1.1K Likes',
                'logo' => Storage::url('ClinicSeederLogo/DermstressClinic.png')
            ],
            [
                'name' => 'Templora Dermatologica Manila Branch',
                'address' => 'manila lotus hotel branch - 1227 A. Mabini St. cor. P. Faura St. Ermita, Manila, Philippines, 1000',
                'latitude' => 14.5779275,
                'longitude' => 120.9784184,
                'operation_hours' => 'Always Open',
                'specialization' => 'Slimming and Cosmetic Surgery',
                'phonenumber' => '09175628367',
                'health_cards' => 'N/A',
                'ratings' => '0',
                'years_of_operation' => '3',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => '500 Php',
                'facebook_link' => 'https://www.facebook.com/temploramanilaclinic/reviews_given',
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '3.5K Likes',
                'logo' => Storage::url('ClinicSeederLogo/TemploraDermatologica.png')
            ],
            [
                'name' => 'The Grace Clinic',
                'address' => 'Unit 917 Broadview Tower 1396 Mayhaligue St., Sta. Cruz, Manila, Manila, Philippines',
                'latitude' => 14.6090806,
                'longitude' => 120.9702129,
                'operation_hours' => 'Always Open',
                'specialization' => 'Aesthetics',
                'phonenumber' => '09052184674',
                'health_cards' => 'DO NOT ACCEPT',
                'ratings' => '0',
                'years_of_operation' => '2',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => 'N/A',
                'facebook_link' => 'https://www.facebook.com/media/set/?set=a.125540463563602&type=3',
                'website_link' => null,
                'walk_ins' => ' Walk-ins or appointments are welcome',
                'popularity' => '1.1K Likes',
                'logo' => Storage::url('ClinicSeederLogo/TheGraceClinic.png')
            ],
            [
                'name' => 'Flawless Face and Body Clinic',
                'address' => 'SM City Manila, San Marcelino St Concepcion cor. Arroceros, Lower Ground, Manila, 1005',
                'latitude' => 14.5897108,
                'longitude' => 120.9804845,
                'operation_hours' => 'Monday - Sunday: 10:00 AM - 9:00 PM',
                'specialization' => 'N/A',
                'phonenumber' => '09178027644',
                'health_cards' => 'N/A',
                'ratings' => '0',
                'years_of_operation' => '22',
                'parking_spot' => 'YES',
                'clinic_type' => 'PRIVATE',
                'consultation_fee' => 'N/A',
                'facebook_link' => 'https://www.facebook.com/FlawlessFaceandBody',
                'website_link' => 'https://flawless.com.ph/?fbclid=IwY2xjawFVswlleHRuA2FlbQIxMAABHX9g4GDHIRqSZf_gSLopSe7nN3Jy-GykN8czCuhP1C4zLLNmGQnJE2DfhQ_aem_kh0uxPVhH82_k7FLq3Uztg',
                'walk_ins' => 'N/A',
                'popularity' => '852K Likes',
                'logo' => Storage::url('ClinicSeederLogo/FlawlessFaceandBodyClinic.png')
            ],

        ];

        // Insert each clinic into the database
        foreach ($clinics as $clinic) {
            Clinics::create($clinic);
        }
    }
}